In [1]:
using LinearAlgebra

function TEN(opsvec)
    N = size(opsvec,1)

    O = opsvec[1]
    for i=2:N
        O = kron(O,opsvec[i])
    end

    return O
end

function trace(ρ)
    return sum(diag(ρ))
end

function negativity(ρ)
    N = 0
    for λ in eigvals(ρ)
        N += abs(λ)-λ
    end
    return N/2.
end

I = [1 0; 0 1]
X = [0 1; 1 0]
Y = [0 -im; im 0]
Z = [1 0; 0 -1]

2×2 Array{Int64,2}:
 1   0
 0  -1

## From the data of Jie for d=2

In [4]:
#### 2-bodies RDM
xx = -0.6071972885826854
ρ2 = (1/4.)*(TEN([I,I])+xx*TEN([X,X])+xx*TEN([Y,Y])+xx*TEN([Z,Z]))
println("")
println("")
println("######## 2-bodies RDM ########")
println("")
println("Trace       : ", trace(ρ2))
println("")
println("Eigenvalues :",eigvals(ρ2))
println("")
println("Negativity  :", negativity(ρ2))

#### 4-bodies RDM
x1x2 = -0.6071972885826854
x1x3 = 0.28515948851967665
x1x4 = -0.2913634119814824
xxxx = 0.7141050431052273
xxyy = 0.4905291292659697
xyxy = -0.06502573640772506
xyyx = 0.2887619329816117


X12     = x1x2*(TEN([X,X,I,I])+TEN([Y,Y,I,I])+TEN([Z,Z,I,I]) + TEN([I,X,X,I])+TEN([I,Y,Y,I])+TEN([I,Z,Z,I]) + TEN([I,I,X,X])+TEN([I,I,Y,Y])+TEN([I,I,Z,Z]))
X13     = x1x3*(TEN([X,I,X,I])+TEN([Y,I,Y,I])+TEN([Z,I,Z,I]) + TEN([I,X,I,X])+TEN([I,Y,I,Y])+TEN([I,Z,I,Z]))
X14     = x1x4*(TEN([X,I,I,X])+TEN([Y,I,I,Y])+TEN([Z,I,I,Z]))
XXXX    = xxxx*(TEN([X,X,X,X])+TEN([Y,Y,Y,Y])+TEN([Z,Z,Z,Z]))
XXYY    = xxyy*(TEN([X,X,Y,Y])+TEN([X,X,Z,Z]) + TEN([Y,Y,X,X])+TEN([Y,Y,Z,Z]) + TEN([Z,Z,X,X])+TEN([Z,Z,Y,Y]))
XYXY    = xyxy*(TEN([X,Y,X,Y])+TEN([X,Z,X,Z]) + TEN([Y,X,Y,X])+TEN([Y,Z,Y,Z]) + TEN([Z,X,Z,X])+TEN([Z,Y,Z,Y]))
XYYX    = xyyx*(TEN([X,Y,Y,X])+TEN([X,Z,Z,X]) + TEN([Y,X,X,Y])+TEN([Y,Z,Z,Y]) + TEN([Z,X,X,Z])+TEN([Z,Y,Y,Z]))

ρ4 = (1/16.)*(TEN([I,I,I,I])+X12+X13+X14+XXXX+XXYY+XYXY+XYYX)
println("")
println("")
println("######## 4-bodies RDM ########")
println("")
println("Trace       : ", trace(ρ4))
println("")
println("Eigenvalues :",eigvals(ρ4))
println("")
println("Negativity  :", negativity(ρ4))




######## 2-bodies RDM ########

Trace       : 1.0 - 0.0im

Eigenvalues :[0.09820067785432865, 0.09820067785432865, 0.09820067785432865, 0.705397966437014]

Negativity  :0.0


######## 4-bodies RDM ########

Trace       : 1.0000000000000002 + 0.0im

Eigenvalues :[-0.019781926381226392, -0.01978192638122638, -0.019781926381226365, -0.015129566456040227, -0.015129566456040211, -0.01512956645604015, 0.010696761059111493, 0.0106967610591115, 0.010736831742768715, 0.010736831742768758, 0.010736831742768776, 0.055650641023521435, 0.09564840031819094, 0.09564840031819097, 0.09564840031819104, 0.7085346191871762]

Negativity  :0.10473447851179973


## From the data of Jie for d=4

In [7]:
#### 2-bodies RDM
xx = -0.6020075865592056
ρ2 = (1/4.)*(TEN([I,I])+xx*TEN([X,X])+xx*TEN([Y,Y])+xx*TEN([Z,Z]))
println("")
println("")
println("######## 2-bodies RDM ########")
println("")
println("Trace       : ", trace(ρ2))
println("")
println("Eigenvalues :",eigvals(ρ2))
println("")
println("Negativity  :", negativity(ρ2))

#### 4-bodies RDM
x1x2 = -0.6020075865592056
x1x3 = 0.25426361927721614
x1x4 = -0.23143966794223547
xxxx = 0.5305652635758876
xxyy = 0.4655235614464653
xyxy = -0.1310156493944701
xyyx = 0.1960573503151137


X12     = x1x2*(TEN([X,X,I,I])+TEN([Y,Y,I,I])+TEN([Z,Z,I,I]) + TEN([I,X,X,I])+TEN([I,Y,Y,I])+TEN([I,Z,Z,I]) + TEN([I,I,X,X])+TEN([I,I,Y,Y])+TEN([I,I,Z,Z]))
X13     = x1x3*(TEN([X,I,X,I])+TEN([Y,I,Y,I])+TEN([Z,I,Z,I]) + TEN([I,X,I,X])+TEN([I,Y,I,Y])+TEN([I,Z,I,Z]))
X14     = x1x4*(TEN([X,I,I,X])+TEN([Y,I,I,Y])+TEN([Z,I,I,Z]))
XXXX    = xxxx*(TEN([X,X,X,X])+TEN([Y,Y,Y,Y])+TEN([Z,Z,Z,Z]))
XXYY    = xxyy*(TEN([X,X,Y,Y])+TEN([X,X,Z,Z]) + TEN([Y,Y,X,X])+TEN([Y,Y,Z,Z]) + TEN([Z,Z,X,X])+TEN([Z,Z,Y,Y]))
XYXY    = xyxy*(TEN([X,Y,X,Y])+TEN([X,Z,X,Z]) + TEN([Y,X,Y,X])+TEN([Y,Z,Y,Z]) + TEN([Z,X,Z,X])+TEN([Z,Y,Z,Y]))
XYYX    = xyyx*(TEN([X,Y,Y,X])+TEN([X,Z,Z,X]) + TEN([Y,X,X,Y])+TEN([Y,Z,Z,Y]) + TEN([Z,X,X,Z])+TEN([Z,Y,Y,Z]))

ρ4 = (1/16.)*(TEN([I,I,I,I])+X12+X13+X14+XXXX+XXYY+XYXY+XYYX)
println("")
println("")
println("######## 4-bodies RDM ########")
println("")
println("Trace       : ", trace(ρ4))
println("")
println("Eigenvalues :",eigvals(ρ4))
println("")
println("Negativity  :", negativity(ρ4))





######## 2-bodies RDM ########

Trace       : 1.0 - 0.0im

Eigenvalues :[0.0994981033601986, 0.0994981033601986, 0.0994981033601986, 0.7015056899194042]

Negativity  :0.0


######## 4-bodies RDM ########

Trace       : 1.0 + 0.0im

Eigenvalues :[0.0001018795058068557, 0.00010187950580688106, 0.00010187950580688165, 0.00010187980800156194, 0.0001018798080015676, 0.00035699697400268975, 0.0003569969740027044, 0.0003569969740027685, 0.00206920310760531, 0.003410893313305416, 0.003410893313305455, 0.0034108933133054613, 0.11348891431291308, 0.11348891431291308, 0.11348891431291311, 0.6456509849583071]

Negativity  :0.0


In [149]:
function permutationes(vec)
    elements = ["x","y","z"];
    elements2 = ["X","Y","Z"];
    permu = [];
    vecbackup = deepcopy(vec);
    for i=1:3
        for j=1:3
            if j!=i 
                vec = replace(vec, elements[1]=>elements2[i])
                vec = replace(vec,elements[2]=>elements2[j])
                vec = replace(vec,elements[3]=>elements2[3-mod(i+j,3)])
                push!(permu, vec)
                vec = deepcopy(vecbackup)
            end
        end
    end
    
    permu = unique!(permu);
    println(permu)
    return permu
end

permutationes (generic function with 1 method)

In [150]:
permutationes("xxii")

Any["XXii", "YYii", "ZZii"]


3-element Array{Any,1}:
 "XXii"
 "YYii"
 "ZZii"

In [49]:
el = ["x", "y"]

replace("xx", el[1] =>"a")

s = "xy"
for i in s[2:end]
        println(i)
end

y


In [151]:
Pauli = Dict('I'=>[1 0; 0 1], 'X'=>[0 1; 1 0], 'Y'=>[0 -im; im 0], 'Z'=>[1 0; 0 -1])
function strtovec(perm)
    #Pauli = Dict("I"=>[1 0; 0 1], "X"=>[0 1; 1 0], "Y"=>[0 -im; im 0], "Z"=>[1 0; 0 -1])
    operator = zeros(Float64, 2^length(perm[1]),2^length(perm[1]))
    for s in perm
        O = get(Pauli,s[1], NaN)
        for x in s[2:end]
            O = kron(O,get(Pauli,x,NaN))
        end
        operator += O
    end

    return operator
end

strtovec (generic function with 1 method)

In [153]:
strtovec(permutationes("xxyy"));

Any["XXYY", "XXZZ", "YYXX", "YYZZ", "ZZXX", "ZZYY"]


TypeError: TypeError: in typeassert, expected Type, got Int64

In [112]:
oper =  zeros(Float64, 2,2);
s = 'X'
oper += get(Pauli, s, NaN)

2×2 Array{Float64,2}:
 0.0  1.0
 1.0  0.0

In [138]:
cc = permutationes("xxxx")
for s in cc
    O = get(Pauli,s[1], NaN)
    println(O)
    for x in s[2:end]
        println(get(Pauli,x,NaN))
    end
end

[0 1; 1 0]
[0 1; 1 0]
[0 1; 1 0]
[0 1; 1 0]
Complex{Int64}[0 + 0im 0 - 1im; 0 + 1im 0 + 0im]
Complex{Int64}[0 + 0im 0 - 1im; 0 + 1im 0 + 0im]
Complex{Int64}[0 + 0im 0 - 1im; 0 + 1im 0 + 0im]
Complex{Int64}[0 + 0im 0 - 1im; 0 + 1im 0 + 0im]
[1 0; 0 -1]
[1 0; 0 -1]
[1 0; 0 -1]
[1 0; 0 -1]


In [155]:
function permutationes(vec)
    elements = ["x","y","z"];
    elements2 = ["X","Y","Z"];
    permu = [];
    vecbackup = deepcopy(vec);
    for i=1:3
        for j=1:3
            if j!=i 
                vec = replace(vec, elements[1]=>elements2[i])
                vec = replace(vec,elements[2]=>elements2[j])
                vec = replace(vec,elements[3]=>elements2[3-mod(i+j,3)])
                push!(permu, vec)
                vec = deepcopy(vecbackup)
            end
        end
    end
    
    permu = unique!(permu);
    println(permu)
    return permu
end

Pauli = Dict('I'=>[1 0; 0 1], 'X'=>[0 1; 1 0], 'Y'=>[0 -im; im 0], 'Z'=>[1 0; 0 -1])

function strtovec(perm)
    #Pauli = Dict("I"=>[1 0; 0 1], "X"=>[0 1; 1 0], "Y"=>[0 -im; im 0], "Z"=>[1 0; 0 -1])
    operator = zeros(Float64, 2^length(perm[1]),2^length(perm[1]))
    for s in perm
        O = get(Pauli,s[1], NaN)
        for x in s[2:end]
            O = kron(O,get(Pauli,x,NaN))
        end
        operator += O
    end

    return operator
end

function term(t)
   return strtovec(permutationes(t))
end

term (generic function with 1 method)

In [160]:
#### 2-bodies RDM
xx = -0.6020075865592056
ρ2 = (1/4.)*(TEN([I,I])+xx*term("xx"))
println("")
println("")
println("######## 2-bodies RDM ########")
println("")
println("Trace       : ", trace(ρ2))
println("")
println("Eigenvalues :",eigvals(ρ2))
println("")
println("Negativity  :", negativity(ρ2))

#### 4-bodies RDM
x1x2 = -0.6020075865592056
x1x3 = 0.25426361927721614
x1x4 = -0.23143966794223547
xxxx = 0.5305652635758876
xxyy = 0.4655235614464653
xyxy = -0.1310156493944701
xyyx = 0.1960573503151137


X12     = x1x2*(term("xxII")+term("IxxI")+term("IIxx"))
X13     = x1x3*(term("xIxI")+term("IxIx"))
X14     = x1x4*term("xIIx")
XXXX    = xxxx*term("xxxx")
XXYY    = xxyy*term("xxyy")
XYXY    = xyxy*term("xyxy")
XYYX    = xyyx*term("xyyx")

ρ4 = (1/16.)*(TEN([I,I,I,I])+X12+X13+X14+XXXX+XXYY+XYXY+XYYX)
println("")
println("")
println("######## 4-bodies RDM ########")
println("")
println("Trace       : ", trace(ρ4))
println("")
println("Eigenvalues :",eigvals(ρ4))
println("")
println("Negativity  :", negativity(ρ4))

Any["XX", "YY", "ZZ"]


######## 2-bodies RDM ########

Trace       : 1.0 - 0.0im

Eigenvalues :[0.0994981033601986, 0.0994981033601986, 0.0994981033601986, 0.7015056899194042]

Negativity  :0.0
Any["XXII", "YYII", "ZZII"]
Any["IXXI", "IYYI", "IZZI"]
Any["IIXX", "IIYY", "IIZZ"]
Any["XIXI", "YIYI", "ZIZI"]
Any["IXIX", "IYIY", "IZIZ"]
Any["XIIX", "YIIY", "ZIIZ"]
Any["XXXX", "YYYY", "ZZZZ"]
Any["XXYY", "XXZZ", "YYXX", "YYZZ", "ZZXX", "ZZYY"]
Any["XYXY", "XZXZ", "YXYX", "YZYZ", "ZXZX", "ZYZY"]
Any["XYYX", "XZZX", "YXXY", "YZZY", "ZXXZ", "ZYYZ"]


######## 4-bodies RDM ########

Trace       : 1.0 + 0.0im

Eigenvalues :[0.0001018795058068557, 0.00010187950580688106, 0.00010187950580688165, 0.00010187980800156194, 0.0001018798080015676, 0.00035699697400268975, 0.0003569969740027044, 0.0003569969740027685, 0.00206920310760531, 0.003410893313305416, 0.003410893313305455, 0.0034108933133054613, 0.11348891431291308, 0.11348891431291308, 0.11348891431291311, 0.6456509849583071]

Negativity  :0.0
